N8N_API_KEY = "****"
N8N_WEBHOOK_URL_ANALYSIS = "http://vinitestes-qa.duckdns.org/webhook/qa-testgen-analysis"
N8N_WEBHOOK_URL_MATRIX = "http://vinitestes-qa.duckdns.org/webhook/qa-testgen-matrix"
N8N_WEBHOOK_URL_GENERATION = "http://vinitestes-qa.duckdns.org/webhook/qa-testgen-generation"
